name: Deploy Infrastructure

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'terraform/ecr/**'
    branches: [ main ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy-ecr:
    name: Deploy ECR Infrastructure
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      working-directory: terraform/ecr
      run: terraform init
    
    - name: Terraform Plan
      working-directory: terraform/ecr
      run: terraform plan
    
    - name: Terraform Apply
      working-directory: terraform/ecr
      run: terraform apply -auto-approve
    
    - name: Get Role ARN
      working-directory: terraform/ecr
      run: |
        ROLE_ARN=$(terraform output -raw gha_role_arn)
        echo "🔑 GitHub Actions Role ARN: $ROLE_ARN"
        echo "Add this as AWS_ROLE_ARN secret in GitHub repository settings"